### ISSUE TITLE
Invalid party Join codes should update the user

### ISSUE THREAD

**Issue by yochaigal** [yochaigal/kettlewright#113]
**Describe the bug**
Invalid party join codes do not alert the end user that they are invalid!

**To Reproduce**
Try to add a made-up party join code.

**Expected behavior**
The end-user should be prompted with an "invalid join code" pop-up

**Comment by david-stearns** [comment]
your suggestion isn't possible without exposing all join codes to the front end

however, we can make it say "invalid party code" under party, after it has been sumbitted
