### ISSUE TITLE
Warden tools field order

### ISSUE THREAD

**Issue by ThatGuySteve99** [yochaigal/kettlewright#117]
Select fields are positioned below the display area where text information is displayed. 

Logical page order would be to make selection then display generated information.

**Smartphone (please complete the following information):**
 - Device: Galaxy
 - OS: Android
 - Browser: Chrome

**Additional context**
This could be particularly impacting on users of assistive technology as its not clear you have to scroll backwards through the page to find the results you've generated.

**Comment by yochaigal** [comment]
The results should appear at the bottom as you roll them, you only have to scroll up for previous results. That said, I don't think it is much trouble to put the fields on top instead!

**Comment by yochaigal** [comment]
This has been fixed! We'll wait till tonight to push it, though.
