### ISSUE TITLE
Item description text syntax error

### ISSUE THREAD

**Issue by PSCourtney** [yochaigal/kettlewright#118]
Line breaks within the description text causes json syntax error on the character view page.  
![Capture](https://github.com/user-attachments/assets/6801696c-ccac-423e-860c-694361d67d47)

Steps to reproduce.

1. Create custom item
2. Add the following description text 
"Curse Unlife

Once per day Deals 1d4 +2 STR loss to one undead, ignoring armour and resistances" 
4. Go to character view page.
5. See reported error in console. 

What the error breaks:
Character portrait
HP
Inventory 

- Everything else seems to load fine. 

Workaround: Remove the linebreaks.

I've attached my error log. 
[kettlewright.com-1726670232505.log](https://github.com/user-attachments/files/17045706/kettlewright.com-1726670232505.log)

**Comment by david-stearns** [comment]
error should now be fixed. However, currently line breaks do not show in the modal when clicking the (i) icon

**Comment by PSCourtney** [comment]
Yep. Working my end!  👌
