### ISSUE TITLE
When running locally `pipenv shell` fails because pipenv does not support version range specifier (eg.: `python_version = ">3.10"`)

### ISSUE THREAD

**Issue by efsalvarenga** [yochaigal/kettlewright#121]
**Describe the bug**
When running locally `pipenv shell` fails because pipenv does not support version range specifier (eg.: `python_version = ">3.10"`)

**To Reproduce**
1. Run locally following the steps on README.
2. When running `pipenv shell` it fails: `Error: Python version range specifier '>3.10' is not supported. Please use an absolute version number or specify the path to the Python executable on Pipfile.`

**Expected behavior**
The virtual environment would have been created

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 14.6.1 (23G93)
 - Apple Silicon M2
 - Zch
 - Python 3.12

**Additional context**

**Comment by yochaigal** [comment]
Thanks, I think I will just remove the requirement completely.
