### ISSUE TITLE
Cutpurse's Gildfinger Default Charges Set to 1/0

### ISSUE THREAD

**Issue by ThackeryBinx286** [yochaigal/kettlewright#128]
The Gildfinger item automatically sets itself to 0 charges during character creation (should be 1/1, but defaults to 1/0). I haven't noticed this on other items from Backgrounds, but it might be worth checking. 
![Gildfinger1](https://github.com/user-attachments/assets/7c551024-7bf5-423b-9e2c-c168503be1fe)
![Gildfinger2](https://github.com/user-attachments/assets/e0a81030-eb72-44ea-b0c2-fc6d16257367)

**Comment by yochaigal** [comment]
Ah, fixed! You will need to re-add the item manually but future character gen will be correct.
