### ISSUE TITLE
Containers of Slot size > 18 causes 'Save' button to stop working

### ISSUE THREAD

**Issue by hrohawkins** [yochaigal/kettlewright#129]
**Describe the bug**
Can't save changes to a character after creating a container with greater than 18 slots.

**To Reproduce**
1. Go to 'Characters'
2. Click on 'New Character'
  2a. Anything is fine, roll all random and click 'Save Character'
4. Click 'Edit'
5. Click '+ Container'
6. Name your container and set the 'Slots' value to anything over 18 (e.g. 19)
7. Click 'Save' to save the container
8. Click 'Save' to save the character
9. Nothing happens, your character changes are not saved

**Expected behavior**
The character should save with the new container added.

**Screenshots**
![image](https://github.com/user-attachments/assets/28fb08df-f931-451a-be30-29d1fabc6563)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 130.0.1

**Additional context**
The ability to add containers of larger sizes would be good, since it allows for magic container items, e.g. "Bag of Holding".

**Comment by yochaigal** [comment]
I think at a minimum we need better user facing notifications of when larger containers can't be added. That said, I don't think THAT many people will need a single container over 20.

**Comment by yochaigal** [comment]
Javascript error from the browser when saving 19 or more slot containers:
`edit/:1 An invalid form control with name='' is not focusable. <input class=​"input modal-field" type=​"number" min=​"0" max=​"18" placeholder=​"slots" id=​"edit-container-modal-slots-field">​`

**Comment by yochaigal** [comment]
@david-stearns obviously we can change the limit there to something higher, but we should add a modal/error window that says something like "x slot maximum"

**Comment by david-stearns** [comment]
What should the maximum slots and load be? What should the max characters for a name be?

**Comment by yochaigal** [comment]
I think 25 is fine. Max characters is probably 16? 12?
