### ISSUE TITLE
Notes fields are no longer scrollable

### ISSUE THREAD

**Issue by yochaigal** [yochaigal/kettlewright#170]
We should either increase the notes field default lines or make a scrollbar:

![image](https://github.com/user-attachments/assets/59e6b1fe-134d-4359-9b71-5812c6beea4b)

**Comment by oswida** [comment]
This field should autoresize (proper listener are connected after DOM is settled). I suppose it could be an effect of some browser optimization, "notes" field is located at the end of page, initially invisible during first rendering. Maybe browser does not find this element.
