### ISSUE TITLE
Internal Server Error on some characters

### ISSUE THREAD

**Issue by Surinawz** [yochaigal/kettlewright#171]
**Describe the bug**
Some character sheets will not load and only give an internal server error

**To Reproduce**
1. Opened Kettlewright.
2. Clicked on a character
3. Received Internal Server Error page

**Expected behavior**
Character sheet loas as normal

**Screenshots**
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [e.g. chrome, safari] Edge

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yochaigal** [comment]
Hello! Yes, there is an issue with the latest version. I've restored the old application; everything should be accessible now.

**Comment by oswida** [comment]
For that, I would need some logs from production server. Internal server error means backend failed, so I need to look there.

**Comment by yochaigal** [comment]
> For that, I would need some logs from production server. Internal server error means backend failed, so I need to look there.

It occurs for some of mine as well, and I can provide logs.

**Comment by yochaigal** [comment]
Here you go:

```
User 1 disconnected
character
server=127.0.0.1:8000//socket.io/ client=172.17.0.1:48546 socket shutdown error: [Errno 9] Bad file descriptorERROR:app:Exception on /users/yochaigal/characters/aria/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/main.py", line 428, in character
    inventory.decorate()
  File "/app/app/lib/inventory.py", line 68, in decorate
    curr_slots = self.container_slots(c)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/lib/inventory.py", line 58, in container_slots
    load = cnt_load[int(it["carrying"])]
           ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 1
^Ccontext canceled
```
