### ISSUE TITLE
Custom Images No Longer Work

### ISSUE THREAD

**Issue by bjj1478** [yochaigal/kettlewright#177]
When you go to edit a new character, when you paste a custom image URL into the custom image field and save, the image is not shown as the character's portrait.

1. Create a new character
2. Edit character
3. Click on portrait to edit it
4. Paste image URL and click save

**Expected behavior**
The new portrait should be the custom image URL you entered

**Comment by yochaigal** [comment]
Confirmed.

**Comment by yochaigal** [comment]
When rolling up a new character the custom image URL does stick around. Afterwards it is not editable.

**Comment by yochaigal** [comment]
Example using https://i.imgur.com/OvDMQcy.png

[Kooha-2024-12-14-14-09-46.webm](https://github.com/user-attachments/assets/ac6cb6b9-df6e-4ef2-98fd-da583f2b06ec)

**Comment by yochaigal** [comment]
> When you go to edit a new character, when you paste a custom image URL into the custom image field and save, the image is not shown as the character's portrait.
> 
> 1. Create a new character
> 2. Edit character
> 3. Click on portrait to edit it
> 4. Paste image URL and click save
> 
> **Expected behavior** The new portrait should be the custom image URL you entered

Can you tell me if this works for you? It does with me.

**Comment by bjj1478** [comment]
Yes, editing a character and switching to custom images is working for me now.
