### ISSUE TITLE
Armour score not showing correctly in character preview

### ISSUE THREAD

**Issue by GiannisGG** [yochaigal/kettlewright#192]
**Describe the bug**
A character with armour shows as **Armor: 0** in the preview ("Characters" page).

**To Reproduce**
1. Create a character
2. Give then some items that increase armour
3. Check that their armour is greater than 0 in sheet.
4. Go to "Characters" page and check the character's preview: it shows 0.

**Expected behavior**
Preview should properly reflect armour updates. 

**Screenshots**
![IMG_2374](https://github.com/user-attachments/assets/30139628-1f27-421c-919d-742b21cb68aa)
![IMG_2375](https://github.com/user-attachments/assets/5562c29b-c32c-4611-881f-74107bb1aeb9)

**Desktop (please complete the following information):**
Not tested on desktop. 

**Smartphone (please complete the following information):**
 - Device: iphone 12 pro Max
 - OS: iOS 18.1.1
 - Browser: Brave

**Additional context**

**Comment by yochaigal** [comment]
Confirmed!

![image](https://github.com/user-attachments/assets/adb27dc7-c0df-4b47-a9d0-8d31d56326d0)

**Comment by yochaigal** [comment]
This is fixed, however you will need to edit your character for the armor values to update!
